# Generated by Django 4.1.3 on 2022-11-29 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("libraryModel", "0002_alter_ebooks_genre"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ebooks",
            old_name="Author",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="ebooks",
            old_name="Favorite",
            new_name="favorite",
        ),
        migrations.RenameField(
            model_name="ebooks",
            old_name="Genre",
            new_name="genre",
        ),
        migrations.RenameField(
            model_name="ebooks",
            old_name="Review",
            new_name="review",
        ),
        migrations.RenameField(
            model_name="ebooks",
            old_name="Title",
            new_name="title",
        ),
    ]
